device: cpu
seed: 2020
# dataset: cora
dataset: citeseer
# dataset: pubmed
# dataset: reddit
E: 3 # dropout probability
n_epochs: 2000
model_type: GCN
# model_type: MLP
split_method: random_choice
# split_method: community_detection
# split_method: b_min_cut
# split_method: ub_min_cut
num_clients: 10
split: 11 # num_clients + 1
